server:
   port: 8008

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HealthRules
    username: postgres
    password: temp1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true